### ISSUE TITLE
File Icons Replace Change Icons

### ISSUE THREAD

**Issue by kryzet** [catppuccin/github-file-explorer-icons#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you on the latest version of the extension?

- [X] I am on the latest version of the extension.

### What browser are you using?

Firefox

### What issue are you experiencing?

On a commit page on GitHub, the icons that do not represent files in particular but rather the changes thereof are replaced with the actual file icons, and without checking every file on that page it is unclear what was added, removed, or modified. I think it would make sense for these icons to be left unchanged.
![image](https://github.com/user-attachments/assets/ae2b5347-62dd-445e-a600-d2f5eca1f755)
![image](https://github.com/user-attachments/assets/f9be7362-6d0a-45e3-8638-ceff2b601c12)

**Comment by uncenter** [comment]
I see, thanks for bringing this up. I personally prefer just the normal file icons, but I can change the default (and add a toggle to enable the current behavior) to use the diff icon (https://preview.iconify.design/catppuccin/?icon-filter=diff) for changed files, and I'll look into requesting a moved file icon. Are there any other icons that GitHub uses in that view besides changed and moved files? Any folder icons besides the default?

**Comment by kryzet** [comment]
> I see, thanks for bringing this up. I personally prefer just the normal file icons, but I can change the default (and add a toggle to enable the current behavior) to use the diff icon (https://preview.iconify.design/catppuccin/?icon-filter=diff) for changed files, and I'll look into requesting a moved file icon.

That looks nice. Good luck!
> Are there any other icons that GitHub uses in that view besides changed and moved files? Any folder icons besides the default?

I think there are also the icons for addition and deletion of files. Not sure if there's anything for copying, and it seems folders don't have special icons because [the first commit to the Neovim repository](https://github.com/neovim/neovim/commit/72cf89bce8e4230dbc161dc5606f48ef9884ba70#diff-6564dde987300eefd4094accb02f00f90cd2af7d1cf11cae57dd2adbfb78eb70) did not have icons for folders being added. Maybe all of those icons get loaded on commit pages, and whether an icon is used depends on the commit's changeset. If that's the case, examining network activity during the loading of a commit page will probably reveal all the icons used on such pages, as well as other pages where change details are shown.
