### ISSUE TITLE
The latest update made the icons invisible.

### ISSUE THREAD

**Issue by aileks** [catppuccin/github-file-explorer-icons#30]
As the title says, the icons are now invisible with the latest update. I've tried both Firefox and Chromium, as well as switching to a manual installation, and the icons remain invisible. Downgrading via a manual installation fixes the issue.

![image](https://github.com/catppuccin/github-file-explorer-icons/assets/88669313/a711696b-3708-438d-84ef-43d34b825948)

**Comment by uncenter** [comment]
What versions of Chrome and Firefox are you using?

**Comment by uncenter** [comment]
Was your browser out of date? The latest release uses the newish CSS `:has()` selector which I was guessing might not be supported by your browser(s) - though most now do if you've updated it recently (https://caniuse.com/css-has).
