### ISSUE TITLE
No longer working on main directory listing component

### ISSUE THREAD

**Issue by peterlobster** [catppuccin/github-file-explorer-icons#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you on the latest version of the extension?

- [X] I am on the latest version of the extension.

### What browser are you using?

Microsoft Edge, Google Chrome, Firefox

### What issue are you experiencing?

The icons no longer work on the main page of repos on GitHub. However, it seems to work elsewhere.

![image](https://github.com/catppuccin/github-file-explorer-icons/assets/38382145/3d8f9dba-8fca-4b6f-b98c-edcb92e7c1b2)

![image](https://github.com/catppuccin/github-file-explorer-icons/assets/38382145/8e40de66-3e86-4576-b7a9-e351f9ec20f8)

**Comment by uncenter** [comment]
Thanks! Also just started seeing this. Would you like to give a try at fixing this? Would involve updating the selectors in https://github.com/catppuccin/github-file-explorer-icons/blob/62afc324c55fa0497b1af6f9162e7e6525eac2d3/src/constants.ts#L1-L20. I'll be able to fix this in a few hours either way though :)

**Comment by peterlobster** [comment]
@uncenter Awesome. Thank you. I can still try it out if you'd like. They're still not working; perphaps I need to update or wait for the release.

**Comment by uncenter** [comment]
Are you sure the extension is enabled? `0.7.0` added support for icons on new domains, which requires you to approve the new permissions for those domains - sometimes the popup doesn't appear, so you'll need to go into your extension settings and turn the extension back on.

**Comment by peterlobster** [comment]
@uncenter Ah, yes, I have an older version. Perhaps because I installed it from the Edge Store instead of the Chrome Store. 

![image](https://github.com/catppuccin/github-file-explorer-icons/assets/38382145/7105d3df-7a5b-4801-b5de-421d2bafa8ea)

**Comment by peterlobster** [comment]
@uncenter I uninstalled it, and installed the Chrome Web Store version and it works just fine. Thank you!

**Comment by uncenter** [comment]
Ah yeah I couldn't tell what browser you were using from your original issue, you *were* correct though - the Edge version was out of date since we didn't have automated publishing set up correctly. The newest `0.7.1` is properly published on all stores now though!

**Comment by peterlobster** [comment]
@uncenter Many thanks!
